version: '3.1'

services:
  quiz-app:
    build: .
    restart: always
    container_name: quiz-app
    volumes:
    - ./storage:/app/storage
    environment:
      - TZ=Europe/Tallinn
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - SESSION_SECRET