version: '3.1'

services:
  translate:
    build: .
    restart: always
    environment:
      - TZ=Europe/Tallinn
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - COOKIE_SECRET
    networks:
      - proxy

networks:
  proxy:
    external: true